### ISSUE TITLE
Add Project API

### ISSUE THREAD

**Issue by dghete** [Product-Foundry/business-elements-client-js#7]

**Comment by andrekampert** [comment]
Started working on this already, but feel free to continue

a0f4171..fc3cda7

- List projects
- Get project (needs to be unit tested)

I started creating specialized instances to provide access to underlying resources to prevent clogging up the API and offer some sort of DSL

**Comment by andrekampert** [comment]
+ get project done

**Comment by andrekampert** [comment]
Moved to Pivotal Tracker
